spring:
  application:
    name: workout

  datasource:
    url: jdbc:mysql://localhost:3306/workout_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER:workout_user}
    password: ${MYSQL_PASSWORD:lift123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    # Change this in a production environment!
    secret: ${JWT_SECRET:bXlfc3VwZXJfc2VjcmV0X2tleV9tdXN0X2JlX2F0X2xlYXN0XzMyX2J5dGVzX2xvbmdfMTIzNDU2}
    # 12 Hours in milliseconds
    expiration-ms: ${JWT_EXPIRATION_MS:43200000}
